# Generated by Django 5.1.2 on 2024-11-29 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("start", "0002_remove_product_created_at_product_image_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="image",
            field=models.ImageField(
                default="/media/products/example.jpg", upload_to="products/"
            ),
        ),
    ]
