# Generated by Django 5.1.2 on 2024-11-29 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("start", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="created_at",
        ),
        migrations.AddField(
            model_name="product",
            name="image",
            field=models.ImageField(
                default="/static/assets/img/chem.png", upload_to="products/"
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="whatsapp_url",
            field=models.URLField(default=2),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="product",
            name="description",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="product",
            name="stock",
            field=models.IntegerField(),
        ),
    ]
